language: c
jobs:
  include:
    - stage: test
      name: "Overview"
      script: ./01_overview/test
    - script: ./02_simple_examples/test
      name: "Simple Examples"
    - script: ./03_variables/test
      name: "Variables"