#!/bin/bash

set -eou pipefail

function main {
	for iter in `iterations`; do
		cd $iter && make
	done
}

function iterations {
	root="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
	ls -d $root/*/
}

main